import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminActionForm } from "@/components/admin/admin-action-form";
import { AdminPageHeader, AdminStatus } from "@/components/admin/admin-page-header";
import { ManualEditor } from "@/components/admin/manual-editor";
import { requireAdminSession } from "@/lib/admin-session";
import { prisma } from "@/lib/db";
import { deleteManualChapter, setManualChapterStatus, updateManualChapter } from "../actions";
export default async function EditManualPage({ params }: { params: Promise<{ id: string }> }) { await requireAdminSession(); const { id } = await params; const [chapter,categories,assets]=await Promise.all([prisma.manualChapter.findUnique({where:{id},include:{category:true}}),prisma.manualCategory.findMany({orderBy:{sortOrder:"asc"}}),prisma.mediaAsset.findMany({orderBy:{createdAt:"desc"},take:50})]); if(!chapter) notFound();
  return <div><AdminPageHeader eyebrow="CONTENT / MANUAL" title={chapter.titleZh} description={`${chapter.category.titleZh} / ${chapter.slug}`} backHref="/admin/manual"><AdminStatus status={chapter.status}/></AdminPageHeader><section className="admin-editor-layout"><div className="admin-editor-main"><ManualEditor action={updateManualChapter} submitLabel="保存修改" categories={categories.map(c=>({id:c.id,slug:c.slug,titleZh:c.titleZh}))} mediaOptions={assets.map(a=>({id:a.id,title:a.title,filePath:a.filePath,category:a.category}))} initialValues={{id:chapter.id,slug:chapter.slug,categoryId:chapter.categoryId,titleZh:chapter.titleZh,author:chapter.author,summaryZh:chapter.summaryZh,coverImagePath:chapter.coverImagePath,sortOrder:chapter.sortOrder,markdownZh:chapter.markdownZh}}/></div><aside className="admin-editor-aside"><div className="admin-sticky-actions"><h3>发布操作</h3><AdminActionForm action={setManualChapterStatus} className="" successMessage="文章状态已更新。"><input type="hidden" name="id" value={chapter.id}/><input type="hidden" name="status" value={chapter.status === "PUBLISHED" ? "DRAFT" : "PUBLISHED"}/><button className="button-ghost" type="submit">{chapter.status === "PUBLISHED" ? "设为草稿" : "发布章节"}</button></AdminActionForm><Link className="button-ghost" href={`/manual/${chapter.category.slug}/${chapter.slug}`} target="_blank">前台预览</Link><AdminActionForm action={deleteManualChapter} className="" successMessage="文章已删除。" confirmMessage={`确认删除手册文章「${chapter.titleZh}」？`}><input type="hidden" name="id" value={chapter.id}/><button className="button-ghost danger-text" type="submit">删除章节</button></AdminActionForm></div></aside></section></div>;
}
